### ISSUE TITLE
CI build failures after update to 2.5.4 from 2.5.1

### ISSUE THREAD

**Issue by Matthiee** [Romanx/Cake.Coverlet#40]
Using 2.5.1 the build script is working. 
Using 2.5.4 the build script is broken. 

I was using
`#addin nuget:?package=Cake.Coverlet`

I have a workaround by downgrading to a known working version
`#addin "nuget:?package=Cake.Coverlet&version=2.5.1"`

Log from CI:
```
Acquiring lock for the installation of Cake.Coverlet 2.5.4
Acquired lock for the installation of Cake.Coverlet 2.5.4
Completed installation of Cake.Coverlet 2.5.4
Could not load C:\projects\commandlineparser-core\tools\Addins\Cake.Coverlet.2.5.4\lib\netstandard2.0\Cake.Coverlet.dll (missing Cake.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
Could not load C:\projects\commandlineparser-core\tools\Addins\Cake.Coverlet.2.5.4\lib\netstandard2.0\Cake.Coverlet.dll (missing Cake.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
Compiling build script...
C:/projects/commandlineparser-core/build.cake(37,9): warning CS0162: Unreachable code detected
dotnet-cake.exe : C:/projects/commandlineparser-core/build.cake(80,36): error CS0246: The type or namespace name 'CoverletSettings' could not be found (are you missing a using directive or an assembly reference?)
At C:\projects\commandlineparser-core\build.ps1:152 char:5
+     & "$CakeExePath" ./build.cake $args
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:/projects/com...bly reference?):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by Romanx** [comment]
Hi there,

This looks to be that you're not using the required version of Cake since this version bumped us to the latest v1.0.0

If you move to the latest version of cake then everything should work as before otherwise pinning the version is recommended.

Thanks
